export const Status = {
    REQUESTED: "REQUESTED", 
    BLOCKED: "BLOCKED",
    CANCELLED: "CANCELLED",
    APPROVED: "APPROVED",
    PENDING: "PENDING",
    ASSIGNED: "ASSIGNED",
    PICKEDUP: "PICKEDUP",
    ON_THE_WAY: "ON_THE_WAY",
    DELIVERED: "DELIVERED",
    CONFIRMED: "CONFIRMED",
    RETURNED: "RETURNED",
  }
export type TStatus = "REQUESTED" | "BLOCKED" | "CANCELLED" | "APPROVED" | "PENDING" | "ASSIGNED" | "PICKEDUP" | "ON_THE_WAY" | "DELIVERED" | "CONFIRMED" | "RETURNED"